/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/uExKnn5Itoe
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
export function Collab() {
  return (
    <section className="w-full py-12 md:py-24 lg:py-32">
      <div className="container grid items-center justify-center gap-4 px-4 text-center md:px-6 lg:gap-10">
        <div className="space-y-3">
          <h2 className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl">Our Trusted Partners</h2>
          <p className="mx-auto max-w-[700px] text-muted-foreground md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed">
            We're proud to collaborate with industry-leading companies to bring you the best products and services.
          </p>
        </div>
        <div className="flex items-center justify-center gap-12">
          <img
            src="/placeholder.svg"
            width="140"
            height="70"
            alt="Partner Logo 1"
            className="aspect-[2/1] overflow-hidden rounded-lg object-contain object-center"
          />
          <img
            src="/placeholder.svg"
            width="140"
            height="70"
            alt="Partner Logo 2"
            className="aspect-[2/1] overflow-hidden rounded-lg object-contain object-center"
          />
          <img
            src="/placeholder.svg"
            width="140"
            height="70"
            alt="Partner Logo 3"
            className="aspect-[2/1] overflow-hidden rounded-lg object-contain object-center"
          />
        </div>
      </div>
    </section>
  )
}
