/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/A2iMGdDpUGQ
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

import { ClockIcon, MailIcon, MapPinIcon, PhoneIcon } from "lucide-react";

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
export default function Footer() {
  return (
    <footer className="bg-muted py-12 md:py-16 lg:py-20">
      <div className="container mx-auto max-w-3xl grid grid-cols-1 gap-8 md:grid-cols-2 lg:gap-12">
        <div className="space-y-4">
          <h2 className="text-2xl font-bold">Thông tin liên hệ</h2>
          <div className="grid gap-2">
            <div className="flex items-center gap-2">
              <PhoneIcon className="h-5 w-5 text-muted-foreground" />
              <p>+84 123 456 789</p>
            </div>
            <div className="flex items-center gap-2">
              <MailIcon className="h-5 w-5 text-muted-foreground" />
              <p>info@example.com</p>
            </div>
            <div className="flex items-center gap-2">
              <ClockIcon className="h-5 w-5 text-muted-foreground" />
              <p>Thứ 2 - Thứ 6: 8h - 17h</p>
            </div>
            <div className="flex items-center gap-2">
              <MapPinIcon className="h-5 w-5 text-muted-foreground" />
              <p>
                Cobi Tower 2, 2-4 Đường số 8, Tân Phú, quận 7, Thành phố Hồ Chí
                Minh
              </p>
            </div>
          </div>
        </div>
        <img
          src="/placeholder.svg"
          width={500}
          height={400}
          alt="Contact"
          className="mx-auto w-full max-w-[500px] rounded-lg object-cover"
        />
      </div>
    </footer>
  );
}
