/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/qhXweKJSfe1
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
export function Target() {
  return (
    <section className="w-full py-12 md:py-24 lg:py-32">
      <div className="container grid items-center gap-6 px-4 md:px-6 lg:grid-cols-2 lg:gap-12">
        <img
          src="/placeholder.svg"
          width="550"
          height="550"
          alt="Target Audience"
          className="mx-auto aspect-video overflow-hidden rounded-xl object-cover object-center sm:w-full"
        />
        <div className="space-y-4">
          <h2 className="text-3xl font-bold tracking-tighter md:text-4xl/tight">Our Target Audience</h2>
          <ul className="grid gap-2">
            <li className="flex items-center rounded-md border px-4 py-2">
              <CheckIcon className="mr-2 h-4 w-4" />
              Các lập trình viên đang làm việc tại Việt Nam
            </li>
            <li className="flex items-center rounded-md border px-4 py-2">
              <CheckIcon className="mr-2 h-4 w-4" />
              Sinh viên tốt nghiệp đại học đang tìm việc trong mảng lập trình
            </li>
            <li className="flex items-center rounded-md border px-4 py-2">
              <CheckIcon className="mr-2 h-4 w-4" />
              Học viên của dự án K-Tech College 2024
            </li>
            <li className="flex items-center rounded-md border px-4 py-2">
              <CheckIcon className="mr-2 h-4 w-4" />
              Người mong muốn làm việc tại các công ty Hàn Quốc
            </li>
          </ul>
        </div>
      </div>
    </section>
  )
}

function CheckIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M20 6 9 17l-5-5" />
    </svg>
  )
}
