/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/qhXweKJSfe1
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

import { Files, GraduationCap, Luggage, Users } from "lucide-react";
import Image from "next/image";

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
export function Target() {
  return (
    <section className="w-full py-12 md:py-24 lg:py-32">
      <div className="container grid items-center gap-6 px-4 md:px-6 lg:grid-cols-2 lg:gap-12">
        <Image
          src="https://res.cloudinary.com/dk3pxmymh/image/upload/v1719387574/likelion/ktc-jobfair-landing/%C4%90%E1%BB%91i%20t%C6%B0%E1%BB%A3ng%20tham%20gia.png"
          width="563"
          height="420"
          alt="Target"
          className="mx-auto aspect-video overflow-hidden rounded-xl object-cover object-center sm:w-full"
        />
        <div className="space-y-4">
          <h2 className="text-3xl font-bold tracking-tighter md:text-4xl/tight">
            Đối tượng tham gia
          </h2>
          <ul className="grid gap-10">
            <li className="flex items-center rounded-md border px-4 py-2">
              <Users className="mr-4 size-4" />
              Các lập trình viên đang làm việc tại Việt Nam
            </li>
            <li className="flex items-center rounded-md border px-4 py-2">
              <Files className="mr-4 size-4" />
              Sinh viên tốt nghiệp đại học đang tìm việc trong mảng lập trình
            </li>
            <li className="flex items-center rounded-md border px-4 py-2">
              <GraduationCap className="mr-4 size-4" />
              Học viên của dự án K-Tech College 2024
            </li>
            <li className="flex items-center rounded-md border px-4 py-2">
              <Luggage className="mr-4 size-4" />
              Người mong muốn làm việc tại các công ty Hàn Quốc
            </li>
          </ul>
        </div>
      </div>
    </section>
  );
}
